#' Request for data on land cover changes from the CDL
#'
#' A function that makes HTTP GET requests for cropland change analysis by comparing the pixels of the cropland area defined by AOI between two given years (year1 and year2).
#' This function implements the GetCDLComp service provided by the CropScape \url{https://nassgeodata.gmu.edu/CropScape}.
#'
#' The GetCDLComp service makes pixel-to-pixel comparisons of cropland covers. This is done by merging the two raster files in year1 and year2 and then count the pixels by groups
#' of cropland cover changes. Note that only the rasters with the same spatial resolutions and coordinates could be directly merged together. However, the spatial resolution for 2006, 2007
#' rasters are at 56-meter, while the rasters in other years have 30-meter resolution. Consequently, the rasters in 2005 and 2006 cannot be directly merged togather, so are the rasters
#' in 2007 and 2008. The CropScape addresses this issue by resampling the finer resolution raster to thesame resolution of the coarser ones, making all the raster datasets the sameresolution.
#' The resampling uses the nearest neighbor resamplingmethod, which assigns values using data in the nearest grid cell found in the input raster.
#'
#' In rare cases, the CropScape cannot generate the output due to some technical iusses. For example, the county boundaries in two different years are different, so the raster files for the
#' same county in the two years cannot be merged and compared. We address this issue by merging the raster files using~\code{inner_join} -- merging grids where we can. A warning message
#' would show up if the returned file is not generated by CropScape web service. There are also cases that the raw CDL raster file cannot be downloaded or loaded, these issues cannot be
#' solved, and an error message would show up.
#'
#'
#' @param aoi Area of interest. Could be a 5-digit FIPS code of a county, three coordinates that defines a triangle,
#' or four corner points that defines a rectangle (or a box), or a single coordinate. The default coordinate system used by CDL is a projected
#' coordinate system called Albers projection (or Albers equal-area conic projection). Users could specify coordinates based on a
#' different coordinate system (defined by the \code{crs} argument), including the geographic coordinate system such as latitude-longitude.
#' @param year1 Crop year. Should be a 4-digit numerical value.
#' @param year2 Crop year. Should be a 4-digit numerical value.
#' @param type Type of AOI. 'f' for county, 'ps' for triangle with multiple coordinates, 'b' for box with four corner points, 'p' for a single coordinate.
#' @param mat TRUE/FALSE. If TRUE (default), return a data table. If FALSE, return a raster file;
#' @param crs Coordinate system. NULL if use the default coordinate system (e.g., Albers projection); Use '+init=epsg:4326' for longitude/latitude.
#'
#' @return
#' The function returns a data table or a raster file.
#'
#' @export
#'
#' @examples
#'\dontrun{
#' # Example 1. Retrieve data for the Champaign county in Illinois (FIPS = 17109) in 2017-2018.
#' data <- GetCDLComp(aoi = '17019', year1 = 2017, year2 = 2018, type = 'f')
#' head(data, 5)
#'
#' # Example 2. Retrieve data for a triangle defined by three coordinates in 2017-2018.
#' aoi <- c(175207,2219600,175207,2235525,213693,2219600)
#' data <- GetCDLComp(aoi = aoi, year1 = 2017, year2 = 2018, type = 'ps')
#' head(data, 5)
#'
#' # Example 3. Retrieve data for a rectangle box defined by four corner points in 2018.
#' data <- GetCDLComp(aoi = c(130783,2203171,153923,2217961), year1 = 2017, year2 = 2018, type = 'b')
#' head(data, 5)
#'}
GetCDLComp <- function(aoi, year1, year2, type, mat = TRUE, crs = NULL){
  targetCRS <- "+proj=aea +lat_1=29.5 +lat_2=45.5 +lat_0=23 +lon_0=-96 +x_0=0 +y_0=0 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs"

  if(!type %in% c('f', 'ps', 'b')) stop('The type value is wrong.')

  if(type == 'f'){
    data <- GetCDLCompF(fips = aoi, year1 = year1, year2 = year2, mat = mat)
  }

  if(type == 'ps'){
    if(length(aoi) < 6) stop('For points, at least 6 values (3 coordinates) have to be provided for aoi.')
    if(!is.null(crs)){
      numps <- length(aoi) # Number of points
      oldpoints <- sp::SpatialPoints(cbind(aoi[seq(1, numps, by = 2)], aoi[seq(2, numps, by = 2)]), sp::CRS(crs))
      newpoints <- sp::spTransform(oldpoints, targetCRS)
      aoi <- paste0(as.vector(t(newpoints@coords)), collapse = ',')
    }
    data <- GetCDLCompPs(points = aoi, year1 = year1, year2 = year2, mat = mat)
  }

  if(type == 'b'){
    if(length(aoi) != 4) stop('For box, 4 values (2 coordinate points) have to be provided for aoi.')
    if(!is.null(crs)){
      numps <- length(aoi) # Number of points
      oldpoints <- sp::SpatialPoints(cbind(aoi[seq(1, numps, by = 2)], aoi[seq(2, numps, by = 2)]), sp::CRS(crs))
      newpoints <- sp::spTransform(oldpoints, targetCRS)
      aoi <- paste0(as.vector(t(newpoints@coords)), collapse = ',')
    }
    data <- GetCDLCompB(box = aoi, year1 = year1, year2 = year2, mat = mat)
  }
  return(data)
}



